import type { ToolDefinition } from '@/shared/types/tool'

export const WEB_VERSION = 'v1.3.3'

export const tools: ToolDefinition[] = [
  {
    id: 'json-formatter',
    name: 'Formateador JSON',
    description: 'Formatea y valida JSON localmente en tu navegador.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.5.3',
  },
  {
    id: 'json-table',
    name: 'JSON a tabla',
    description: 'Convierte JSON (incluyendo objetos anidados) a tabla y exporta CSV/Excel.',
    category: 'Datos',
    status: 'ready',
    version: '1.0.1',
  },
  {
    id: 'base64',
    name: 'Base64 Texto',
    description: 'Codifica y decodifica texto de forma rapida.',
    category: 'Datos',
    status: 'ready',
    version: '1.1.2',
  },
  {
    id: 'base64-image',
    name: 'Base64 a imagen',
    description: 'Convierte una o varias cadenas Base64 en imagenes.',
    category: 'Datos',
    status: 'ready',
    version: '1.2.1',
  },
  {
    id: 'base64-pdf',
    name: 'Base64 a PDF',
    description: 'Convierte una o varias cadenas Base64 en archivos PDF.',
    category: 'Datos',
    status: 'ready',
    version: '1.2.1',
  },
  {
    id: 'sql-formatter',
    name: 'Formateador SQL',
    description: 'Formatea consultas SQL con soporte multi dialecto.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.3.1',
  },
  {
    id: 'code-minifier',
    name: 'Minify/Expand JS-CSS',
    description: 'Minifica y expande JavaScript o CSS desde texto o archivo.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.0.1',
  },
  {
    id: 'regex-tool',
    name: 'Expresiones regulares',
    description: 'Crear, probar, debuggear y exportar regex.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.5.2',
  },
  {
    id: 'sql-mongo-converter',
    name: 'SQL a MongoDB',
    description: 'Convierte SELECT SQL simples a queries MongoDB.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.2.2',
  },
  {
    id: 'json-model-generator',
    name: 'JSON a clases',
    description: 'Genera clases desde JSON en C#, TypeScript, Java, Python, Kotlin y Go.',
    category: 'Generadores de codigo',
    status: 'ready',
    version: '1.2.1',
  },
  {
    id: 'jwt-builder',
    name: 'JWT Builder',
    description: 'Crea tokens JWT y firma HS256 localmente.',
    category: 'Tokens e identidad',
    status: 'ready',
    version: '1.0.1',
  },
  {
    id: 'jwt',
    name: 'Visualizador JWT',
    description: 'Decodifica header y payload para inspeccion.',
    category: 'Tokens e identidad',
    status: 'ready',
    version: '1.1.2',
  },
  {
    id: 'uuid',
    name: 'Generador UUID',
    description: 'Genera UUID v4 y valida su formato.',
    category: 'Tokens e identidad',
    status: 'ready',
    version: '1.0.1',
  },
  {
    id: 'url-codec',
    name: 'Codificador URL',
    description: 'Escapa y desescapa contenido para URLs.',
    category: 'Utilidades web',
    status: 'ready',
    version: '1.0.2',
  },
  {
    id: 'encoding-suite',
    name: 'Encoder/Decoder extra',
    description: 'HTML, Unicode, Hex y URL-safe Base64.',
    category: 'Utilidades web',
    status: 'ready',
    version: '1.0.2',
  },
  {
    id: 'color-tools',
    name: 'Color Tools',
    description: 'Convierte HEX/RGB/HSL y valida contraste WCAG.',
    category: 'Utilidades web',
    status: 'ready',
    version: '1.0.2',
  },
  {
    id: 'box-shadow-generator',
    name: 'Box Shadow Generator',
    description: 'Genera sombras CSS con preview y salida lista para copiar.',
    category: 'Utilidades web',
    status: 'ready',
    version: '1.0.3',
  },
  {
    id: 'spacing-preview',
    name: 'Border/Spacing Preview',
    description: 'Previsualiza border-radius, padding y margin con CSS exportable.',
    category: 'Utilidades web',
    status: 'ready',
    version: '1.0.3',
  },
  {
    id: 'datetime-tools',
    name: 'DateTime tools',
    description: 'Timezone convert, Unix timestamp e ISO formatter.',
    category: 'Utilidades web',
    status: 'ready',
    version: '1.1.1',
  },
  {
    id: 'id-toolkit',
    name: 'UUID/ULID/KSUID Toolkit',
    description: 'Generador, validador y export batch de IDs.',
    category: 'Tokens e identidad',
    status: 'ready',
    version: '1.1.1',
  },
  {
    id: 'fake-data-generator',
    name: 'Generador fake data',
    description: 'Genera JSON fake con nombres, emails, UUID y fechas.',
    category: 'Datos',
    status: 'ready',
    version: '1.0.1',
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convierte imagenes locales a Data URL/Base64.',
    category: 'Datos',
    status: 'ready',
    version: '1.0.2',
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer/Preview',
    description: 'Minifica SVG, previsualiza y exporta el resultado.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.0.2',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convierte texto entre camelCase, snake_case, kebab-case y mas.',
    category: 'Formateadores',
    status: 'ready',
    version: '1.0.1',
  },
]


